#!/bin/sh -e

export VERSION=`cat apistar/__init__.py | grep __version__ | sed "s/__version__ = //" | sed "s/'//g"`
export PREFIX="venv/bin/"

find apistar -type f -name "*.py[co]" -delete
find apistar -type d -name __pycache__ -delete

${PREFIX}python setup.py sdist
${PREFIX}twine upload dist/* --repository=robbie_pypicloud

echo "You probably want to also tag the version now:"
echo "git tag -a ${VERSION} -m 'version ${VERSION}'"
echo "git push --tags"

rm -r dist
